### ISSUE TITLE
Keyboard localization

### ISSUE THREAD

**Issue by benjaminforras** [JulienKluge/Spedit#44]
Well, this is the best sourcepawn editor, only problem is: I can not type brackets ( [], {}.. etc ), because it doesn't have keyboard localization. ( Many countries have different keyboards. )

I currently use Atom for coding which has keyboard localization plugin, here you can find it: https://atom.io/packages/keyboard-localization ( Source code: https://github.com/andischerer/atom-keyboard-localization )

**Comment by JulienKluge** [comment]
what? This shouldn't happen. I type on a german keyboard and it recognizes everything right.
What Layout do you use?

**Comment by benjaminforras** [comment]
Here you can find the picture of my keyboard what I use: ![img_20160411_163758_1460385498832](https://cloud.githubusercontent.com/assets/10364896/14431028/178e7e04-0004-11e6-8413-ff772c5608bf.jpg)

When I press Alt Gr + F ( G for brackets [] ) it brings up the search/replace window and the 'Go to line' menu
When I press Alt Gr + N for this character '}' it opens up the New File window.  

I think the problem may be the Alt Gr button, because the program thinks it's the (right) ctrl button.

On Windows it is set to Hungarian layout.

**Comment by JulienKluge** [comment]
Fixed and closed.

**Comment by benjaminforras** [comment]
Alt Gr and G still not working ( for character ']' ), it shows the 'Jump to line/Jump to offset' dialog.
